;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        format-code
        ))

(setq mc/cmds-to-run-once
      '(
        eval-buffer
        mouse-save-then-kill
        typescript-insert-and-indent
        ))
